name: rick_and_morty
description: App the Rick and Morty

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  riverpod: ^1.0.3
  share_plus: ^4.0.4
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: en
  class_name: I18n
